version: '3'

services:
  redoc:
    image: redocly/redoc:latest
    container_name: redoc
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      SPEC_URL: openapi/openapi.yml
    ports:
      - "8081:80"
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi
    environment:
      API_URL: openapi/openapi.yml
    ports:
      - "8082:8080"
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger-editor
    ports:
      - "8083:8080"
