version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front"
    target-branch: "develop"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    directory: "/api"
    target-branch: "develop"
    schedule:
      interval: "daily"
