version: "3.9"

services:
  db:
    image: postgres:13.1-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      args:
        WORKDIR: app
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./api:/app
    depends_on:
      - db
    ports:
      - "3004:3000"

  front:
    build:
      context: ./front
      args:
        WORKDIR: app
        CONTAINER_PORT: 3002
    command: yarn run dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "9999:3002"
    depends_on:
      - api
