version: "3.9"

services:
  db:
    container_name: event_db
    image: postgres:13.1-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data

  api:
    container_name: event_api
    tty: true
    stdin_open: true
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_ORIGIN: front:$FRONT_PORT
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      TWITTER_KEY: $TWITTER_KEY
      TWITTER_SECRET: $TWITTER_SECRET
      DOORKEEPER_AUTH_TOKEN: $DOORKEEPER_AUTH_TOKEN
      OAUTH_CONSUMER_KEY: $OAUTH_CONSUMER_KEY
      OAUTH_CONSUMER_SECRET: $OAUTH_CONSUMER_SECRET
      OAUTH_APP_TOKEN: $OAUTH_APP_TOKEN
      RAILS_MAX_THREADS: $RAILS_MAX_THREADS
      RAILS_MASTER_KEY: $RAILS_MASTER_KEY
      REDIS_URL: $REDIS_URL
    volumes:
      - ./api:/app
    depends_on:
      - db
      - redis
    ports:
      - "$API_PORT:$CONTAINER_PORT"

  front:
    container_name: event_front
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: http://api:$API_PORT
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
        FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
        FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_MEASUREMENT_ID: $FIREBASE_MEASUREMENT_ID

    command: yarn run dev
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
    depends_on:
      - api

  redis:
    container_name: event_redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - "./api/tmp/redis:/data"
    expose:
      - 6379
