default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eventfollow_development
  username: mbyk
  password: mbyk

test:
  <<: *default
  database: eventfolllow_test

production:
  <<: *default
  database: eventfollow_production
