default: &default
  adapter: postgresql
  host: db
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: eventfollow_development

test:
  <<: *default
  database: eventfolllow_test

production:
  <<: *default
  database: eventfollow_production
