# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

gem "rails", "~> 6.1.3"
gem "pg", "~> 1.1"
gem "puma", "~> 5.2"
gem "bootsnap", ">= 1.4.4", require: false
gem "kaminari"
gem "hashie"
gem "faraday"
gem "faraday_middleware"
gem "ogp", "0.4.0"
gem "jbuilder", "~> 2.11"
gem "kaminari"
gem "clockwork"
gem "rack-cors"
gem "firebase-auth-rails"
gem "skylight", "~> 5.0"
gem "sentry-ruby"
gem "sentry-rails"
gem "lockbox"

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "factory_bot"
  gem "factory_bot_rails"
  gem "rspec-rails", "~> 5.0"
  gem "trace_location"
end

group :development do
  gem "listen", "~> 3.3"
  gem "spring"
  gem "faraday_curl"
  gem "spring-commands-rspec"
  gem "rubocop-rails", require: false
  gem "rubocop-performance", require: false
end

group :test do
  gem "committee"
  gem "committee-rails"
end

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
