name: api lint

on:
  pull_request:
    paths:
      - "api/**"
      - ".github/workflows/api_lint.yml"
      - "docker-compose.yml"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: 1.8.1
          github_token: ${{ secrets.GITHUB_TOKEN }}
          rubocop_flags: --config api/.rubocop.yml api/
          level: warning
          reporter: github-pr-review 
