name: front lint

on:
  pull_request:
    paths:
      - "front/**"
      - ".github/workflows/front_lint.yml"
      - "docker-compose.yml"

jobs:
  reviewdog_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: yarn setup
        run: cd front && yarn install
      - name: eslint
        run: cd front && yarn run lint | reviewdog -f=eslint -reporter=github-pr-review -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
