name: front test

on:
  pull_request:

jobs:
  front-test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      WORKDIR: ${{ secrets.WORKDIR }}
      FRONT_PORT: ${{ secrets.FRONT_PORT }}
      TWITTER_KEY: ${{ secrets.TWITTER_KEY }}
      TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
      DOORKEEPER_AUTH_TOKEN: ${{ secrets.DOORKEEPER_AUTH_TOKEN }}
      OAUTH_CONSUMER_KEY: ${{ secrets.OAUTH_CONSUMER_KEY }}
      OAUTH_CONSUMER_SECRET: ${{ secrets.OAUTH_CONSUMER_SECRET }}
      OAUTH_APP_TOKEN: ${{ secrets.OAUTH_APP_TOKEN }}
      RAILS_MAX_THREADS: ${{ secrets.RAILS_MAX_THREADS }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      API_PORT: ${{ secrets.API_PORT }}
      CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
    steps:
      - uses: actions/checkout@v2.0.0
      - name: docker-compose up
        run: docker-compose up -d
      - name: test
        run: docker-compose exec -T front yarn run test

