name: front lint

on:
  pull_request:
    paths:
      - "front/**"
      - ".github/workflows/front_lint.yml"
      - "docker-compose.yml"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn setup
        run: cd front && yarn install
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts,.js,.vue --ignore-path .gitignore front'
