name: wakeup front

on:
  schedule:
    - cron: '0,20,40 * * * *'
  push:
    branches:
      - main

jobs:
  wakeup:
    runs-on: ubuntu-latest
    steps:
      - name: wakeup EVENT_FOLLOW_FRONT_URL
        run: curl --head --silent --show-error ${{ secrets.EVENT_FOLLOW_FRONT_URL }}
